sim {
  seed = 5532026

  run {
    durationSeconds = 10
  }

  messages {
    types = [ "CONTROL", "PING", "GOSSIP", "WORK", "ACK" ]
  }

  algorithms {
    enabled = [ "echo", "wave" ]
    initiatorNode = 0
  }

  edgeLabeling {
    default = [ "CONTROL", "PING", "WORK" ]
    overrides = []
  }

  traffic {
    defaultPdf = [
      { msg = "PING", p = 0.50 },
      { msg = "WORK", p = 0.50 }
    ]

    perNodePdf = []
  }

  initiators {
    timers = [
      { node = 0, tickEveryMs = 500, mode = "pdf" }
    ]

    inputs = [
      { node = 0 }
    ]
  }
}
